name: flutter_template_melos
version: 1.0.0

environment:
  sdk: ^3.9.0

dev_dependencies:
  melos: ^7.1.0

workspace:
  - apps/app
  - apps/server
  - packages/core
  - packages/updater
  - packages/restaurant_local_server

melos:
  sdkPath: .fvm/flutter_sdk

  packages:
    - apps/**
    - packages/**

  command:
    bootstrap:
      environment:
        sdk: ">=3.9.0 <4.0.0"
        flutter: ">=3.35.1 <4.0.0"
      hooks:
        # 初始化时生成代码
        post: cd apps/web && pnpm i && pnpm build && cd ../.. && melos run generate

    clean:
      hooks:
        post: melos exec --flutter --concurrency=3 -- "flutter clean"

  scripts:
    generate:
      run: melos exec -c 1 --depends-on build_runner -- dart run build_runner build --delete-conflicting-outputs

    build:android:
      run: |
        melos exec -c 6 --fail-fast -- \
          "cd ../web  && pnpm i && pnpm build && cd ../app && fastforge release --name android"
      description: 构建 android apk
      packageFilters:
        dirExists:
          - android

    build:windows:
      run: |
        melos exec -c 6 --fail-fast -- \
          "cd ../web  && pnpm i && pnpm build && cd ../app && fastforge release --name windows"
      description: 构建 windows exe
      packageFilters:
        dirExists:
          - windows
