name: server
resolution: workspace
version: 1.0.0

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  path: ^1.9.0
  mime: ^1.0.6
  shelf_plus: ^1.0.2
  shelf: ^1.4.2
  shelf_static: ^1.1.3
  shelf_multipart: ^2.0.1
  dart_mappable: ^4.5.0
  dart_jsonwebtoken: ^3.2.0
  shelf_proxy: ^1.0.4
  collection: ^1.19.1
  core: 1.0.0
  app: 1.0.0
  uuid: ^4.5.1
  restaurant_local_server: ^1.0.2

dev_dependencies:
  lints: ^4.0.0
  dart_mappable_builder: ^4.5.0
  test: ^1.25.8
  shelf_router_generator: 1.1.1
  build_runner: any

dependency_overrides:
  web_socket_channel: ^2.4.0
