name: updater
resolution: workspace
version: 1.0.0

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  pub_semver: ^2.2.0
  open_file: ^3.5.10
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
