name: app
resolution: workspace
version: 1.0.0

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  path_provider: ^2.1.5
  path: ^1.9.0
  csv: ^6.0.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  flex_color_scheme: ^8.3.0
  objectbox: ^4.3.0
  objectbox_flutter_libs: any
  injectable: ^2.5.0
  url_launcher: ^6.3.2
  core: 1.0.0
  http_server: 1.0.0
  dart_mappable: ^4.5.0
  server: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  objectbox_generator: any
  injectable_generator: ^2.7.0
  dart_mappable_builder: ^4.5.0
  build_runner: any

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/locales/
    - assets/web/
    - assets/web/assets/
